### ISSUE TITLE
Help: Are user's privacy and their project info being collected and sent to red hat? To what extend does this plugin collect user data.

### ISSUE THREAD

**Issue by encanto-oss** [redhat-developer/intellij-redhat-telemetry#48]

**Comment by adietish** [comment]
Hi @encanto-oss 

Sorry for the late response, we somehow missed your request unfortunately.
This plugin helps us to identify if features are used and if errors happen. You can of course choose not to allow us this and refuse or opt out at any moment in time. 
The data that we collect allows us to identify frequently faced errors and most frequently used actions. Both so that we can fix the errors and improve the most widely used actions. 
We're explicitly prohibited from collecting anything that's unique to user: neither user-, resource- nor cluster-names or anything similar. What we collect is action XY used with a resource type ZX in XY minutes resulting in success or error. We then also collect the IDEA version, Kubernetes version, OS, timezone/country. The latter allows us to know what compatibility we need to provide. All details of what we collect is listed in our document at https://github.com/redhat-developer/intellij-redhat-telemetry/blob/main/USAGE_DATA.md
Our privacy policy is stated at https://developers.redhat.com/article/tool-data-collection.
Hope this answers your legitimate questions.

Cheers
André

**Comment by adietish** [comment]
Feel free to reopen this issue if you feel that you've not got all the answers that you requested.
Closing.
